Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 160, in <module>
    compareGTFs(sys.argv[1], sys.argv[2])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 11, in compareGTFs
    with open(truthGTF, 'r') as tsv:
IOError: [Errno 2] No such file or directory: 'sim0/cufflinks/orig/transcripts.gtf'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 160, in <module>
    compareGTFs(sys.argv[1], sys.argv[2])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 11, in compareGTFs
    with open(truthGTF, 'r') as tsv:
IOError: [Errno 2] No such file or directory: 'sim0/cufflinks/orig/transcripts.gtf'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 160, in <module>
    compareGTFs(sys.argv[1], sys.argv[2])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 11, in compareGTFs
    with open(truthGTF, 'r') as tsv:
IOError: [Errno 2] No such file or directory: 'sim0/cufflinks/orig/transcripts.gtf'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 160, in <module>
    compareGTFs(sys.argv[1], sys.argv[2])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 11, in compareGTFs
    with open(truthGTF, 'r') as tsv:
IOError: [Errno 2] No such file or directory: 'sim0/cufflinks/orig/transcripts.gtf'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 160, in <module>
    compareGTFs(sys.argv[1], sys.argv[2])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 11, in compareGTFs
    with open(truthGTF, 'r') as tsv:
IOError: [Errno 2] No such file or directory: 'sim1/cufflinks/orig/transcripts.gtf'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 160, in <module>
    compareGTFs(sys.argv[1], sys.argv[2])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 11, in compareGTFs
    with open(truthGTF, 'r') as tsv:
IOError: [Errno 2] No such file or directory: 'sim1/cufflinks/orig/transcripts.gtf'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 160, in <module>
    compareGTFs(sys.argv[1], sys.argv[2])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 11, in compareGTFs
    with open(truthGTF, 'r') as tsv:
IOError: [Errno 2] No such file or directory: 'sim1/cufflinks/orig/transcripts.gtf'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 160, in <module>
    compareGTFs(sys.argv[1], sys.argv[2])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 11, in compareGTFs
    with open(truthGTF, 'r') as tsv:
IOError: [Errno 2] No such file or directory: 'sim2/cufflinks/orig/transcripts.gtf'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 160, in <module>
    compareGTFs(sys.argv[1], sys.argv[2])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 11, in compareGTFs
    with open(truthGTF, 'r') as tsv:
IOError: [Errno 2] No such file or directory: 'sim2/cufflinks/orig/transcripts.gtf'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 160, in <module>
    compareGTFs(sys.argv[1], sys.argv[2])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareGTFs.py", line 11, in compareGTFs
    with open(truthGTF, 'r') as tsv:
IOError: [Errno 2] No such file or directory: 'sim3/cufflinks/orig/transcripts.gtf'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 175, in <module>
    compareGTFs(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 11, in compareGTFs
    transcriptsTruth = parsePro(proFile)
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 64, in parsePro
    with open(filename, 'r') as f:
IOError: [Errno 2] No such file or directory: 'all_reps/simulation.pro'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 175, in <module>
    compareGTFs(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 11, in compareGTFs
    transcriptsTruth = parsePro(proFile)
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 64, in parsePro
    with open(filename, 'r') as f:
IOError: [Errno 2] No such file or directory: 'all_reps/simulation.pro'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 175, in <module>
    compareGTFs(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 11, in compareGTFs
    transcriptsTruth = parsePro(proFile)
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 64, in parsePro
    with open(filename, 'r') as f:
IOError: [Errno 2] No such file or directory: 'all_reps/simulation.pro'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 175, in <module>
    compareGTFs(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 11, in compareGTFs
    transcriptsTruth = parsePro(proFile)
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 64, in parsePro
    with open(filename, 'r') as f:
IOError: [Errno 2] No such file or directory: 'all_reps/simulation.pro'
Traceback (most recent call last):
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 175, in <module>
    compareGTFs(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 11, in compareGTFs
    transcriptsTruth = parsePro(proFile)
  File "/scratch0/langmead-fs1/user/jacob/compress-alignments/compareToTruth.py", line 64, in parsePro
    with open(filename, 'r') as f:
IOError: [Errno 2] No such file or directory: 'all_reps/simulation.pro'
